#!/bin/env bash
#
# Code by @EdgarLuck
# Servicio de ayuda https://t.me/EdgarLuck
# Canal de Youtube: https://youtube.com/channel/UCVCklEUJuOhydbySEbY5_eA
# ya no sigas , dejalo :v
#
#
z="
";RBz='tf "';eBz='eso:';Gz='33m'\''';XBz='\r\e';DBz=')/10';CCz='numb';hBz='m[\e';Pz='P='\''\';GCz='${_s';iBz='${R}';nz='o="\';BCz='for ';UBz='}s")';ABz='100/';cCz='p 1';Ez='32m'\''';OCz='Prog';ACz='=100';fz='y="\';Jz='M='\''\';kBz='one/';Qz='Gree';az=''\''';qz='tion';hz='w="\';ez='92m"';gz='93m"';iz='39m"';Nz='W='\''\';bCz='\n'\''';fBz=' \e[';Lz='C='\''\';PBz='e=$(';ZBz='[+]$';dBz='proc';SCz='mber';NBz='-$_d';tz='sBar';oBz='-}\e';xz='s=($';Kz='35m'\''';NCz='01';sBz='W}${';tBz='s}%%';vBz='}';QCz='Bar ';dz='g="\';gBz='1;91';Sz='e[32';FBz='_don';yz='{1}*';uBz='"';Dz='G='\''\';Cz='31m'\''';lBz='/ /#';oz='33m"';JCz='})';ICz='} ${';Vz='\e[5';cBz='ndo ';Iz='34m'\''';xBz='rt=1';Tz='m'\''';KCz='do';yBz='_end';XCz=']\e[';YBz='${B}';LBz='_lef';wBz='_sta';FCz='seq ';aBz='W In';ECz='n $(';qBz='1m] ';IBz='ogre';Mz='36m'\''';PCz='ress';lz='b="\';Oz='37m'\''';HBz='{_pr';nBz='// /';YCz='1;37';Bz='e[1;';mz='94m"';DCz='er i';Rz='n='\''\';MBz='t=40';MCz='p 0.';uz=' {';pBz='[1;9';vz='let ';TBz='done';WBz='left';sz='gres';OBz='one';GBz='e=($';rz=' Pro';BBz='${2}';HCz='tart';Yz='='\''\e';WCz='4m[+';Zz='[90m';VBz='t=$(';TCz='tf '\''';Fz='Y='\''\';Xz='Gris';RCz='${nu';CBz='*100';Hz='B='\''\';LCz='slee';QBz='prin';aCz='sto!';wz='_pro';pz='func';Az='R='\''\';bz='r="\';KBz='4)/1';jz='c="\';SBz='%${_';rBz='\e${';EBz='0';jBz='${_d';bBz='icia';UCz='\n\e';VCz='[1;3';Wz='m\e[';cz='91m"';ZCz='m Li';Uz='Gr='\''';kz='96m"';JBz='ss}*';mBz='}${_';
eval "$Az$Bz$Cz$z$Dz$Bz$Ez$z$Fz$Bz$Gz$z$Hz$Bz$Iz$z$Jz$Bz$Kz$z$Lz$Bz$Mz$z$Nz$Bz$Oz$z$Pz$Bz$Kz$z$Qz$Rz$Sz$Tz$z$Uz$Vz$Wz$Ez$z$Xz$Yz$Zz$az$z$bz$Bz$cz$z$dz$Bz$ez$z$fz$Bz$gz$z$hz$Bz$iz$z$jz$Bz$kz$z$lz$Bz$mz$z$nz$Bz$oz$z$pz$qz$rz$sz$tz$uz$z$vz$wz$sz$xz$yz$ABz$BBz$CBz$DBz$EBz$z$vz$FBz$GBz$HBz$IBz$JBz$KBz$EBz$z$vz$LBz$MBz$NBz$OBz$z$FBz$PBz$QBz$RBz$SBz$TBz$UBz$z$LBz$VBz$QBz$RBz$SBz$WBz$UBz$z$QBz$RBz$XBz$YBz$ZBz$aBz$bBz$cBz$dBz$eBz$fBz$gBz$hBz$iBz$jBz$kBz$lBz$mBz$WBz$nBz$oBz$pBz$qBz$rBz$sBz$wz$sz$tBz$uBz$z$vBz$z$wBz$xBz$z$yBz$ACz$z$BCz$CCz$DCz$ECz$FCz$GCz$HCz$ICz$yBz$JCz$z$KCz$z$LCz$MCz$NCz$z$OCz$PCz$QCz$RCz$SCz$ICz$yBz$vBz$z$TBz$z$QBz$TCz$UCz$VCz$WCz$XCz$YCz$ZCz$aCz$bCz$z$LCz$cCz"
