#!/bin/env bash
#
# Code by @EdgarLuck
# Servicio de ayuda https://t.me/EdgarLuck
# Canal de Youtube: https://youtube.com/channel/UCVCklEUJuOhydbySEbY5_eA
# ya no sigas , dejalo :v
#
#
z="
";lz='b="\';kz='96m"';bz='r="\';KCz='do';OBz='one';oBz='-}\e';fz='y="\';Pz='P='\''\';hz='w="\';mz='94m"';hBz='m[\e';Sz='e[32';UBz='}s")';YCz='1;37';WBz='left';aCz='sto!';HCz='tart';Bz='e[1;';ABz='100/';Ez='32m'\''';cBz='ndo ';Lz='C='\''\';Yz='='\''\e';Dz='G='\''\';NCz='01';BBz='${2}';TCz='tf '\''';JCz='})';DBz=')/10';nBz='// /';ZBz='[+]$';GCz='${_s';VCz='[1;3';qz='tion';QBz='prin';DCz='er i';Vz='\e[5';bBz='icia';uz=' {';sBz='W}${';VBz='t=$(';rBz='\e${';RCz='${nu';yz='{1}*';CBz='*100';SBz='%${_';wz='_pro';KBz='4)/1';Jz='M='\''\';sz='gres';Iz='34m'\''';XBz='\r\e';Tz='m'\''';nz='o="\';ICz='} ${';XCz=']\e[';NBz='-$_d';yBz='_end';Rz='n='\''\';TBz='done';dz='g="\';bCz='\n'\''';vBz='}';oz='33m"';cz='91m"';aBz='W In';IBz='ogre';Fz='Y='\''\';Hz='B='\''\';Gz='33m'\''';mBz='}${_';gz='93m"';pz='func';ECz='n $(';FBz='_don';xBz='rt=1';Qz='Gree';ZCz='m Li';fBz=' \e[';Nz='W='\''\';dBz='proc';Az='R='\''\';uBz='"';pBz='[1;9';az=''\''';RBz='tf "';YBz='${B}';vz='let ';HBz='{_pr';iz='39m"';iBz='${R}';LCz='slee';Oz='37m'\''';FCz='seq ';PBz='e=$(';MCz='p 0.';rz=' Pro';LBz='_lef';eBz='eso:';Xz='Gris';xz='s=($';Uz='Gr='\''';EBz='0';SCz='mber';WCz='4m[+';UCz='\n\e';Mz='36m'\''';gBz='1;91';GBz='e=($';Cz='31m'\''';JBz='ss}*';Zz='[90m';PCz='ress';cCz='p 1';jz='c="\';OCz='Prog';lBz='/ /#';QCz='Bar ';ez='92m"';Kz='35m'\''';tz='sBar';BCz='for ';MBz='t=40';Wz='m\e[';jBz='${_d';ACz='=100';tBz='s}%%';CCz='numb';qBz='1m] ';kBz='one/';wBz='_sta';
eval "$Az$Bz$Cz$z$Dz$Bz$Ez$z$Fz$Bz$Gz$z$Hz$Bz$Iz$z$Jz$Bz$Kz$z$Lz$Bz$Mz$z$Nz$Bz$Oz$z$Pz$Bz$Kz$z$Qz$Rz$Sz$Tz$z$Uz$Vz$Wz$Ez$z$Xz$Yz$Zz$az$z$bz$Bz$cz$z$dz$Bz$ez$z$fz$Bz$gz$z$hz$Bz$iz$z$jz$Bz$kz$z$lz$Bz$mz$z$nz$Bz$oz$z$pz$qz$rz$sz$tz$uz$z$vz$wz$sz$xz$yz$ABz$BBz$CBz$DBz$EBz$z$vz$FBz$GBz$HBz$IBz$JBz$KBz$EBz$z$vz$LBz$MBz$NBz$OBz$z$FBz$PBz$QBz$RBz$SBz$TBz$UBz$z$LBz$VBz$QBz$RBz$SBz$WBz$UBz$z$QBz$RBz$XBz$YBz$ZBz$aBz$bBz$cBz$dBz$eBz$fBz$gBz$hBz$iBz$jBz$kBz$lBz$mBz$WBz$nBz$oBz$pBz$qBz$rBz$sBz$wz$sz$tBz$uBz$z$vBz$z$wBz$xBz$z$yBz$ACz$z$BCz$CCz$DCz$ECz$FCz$GCz$HCz$ICz$yBz$JCz$z$KCz$z$LCz$MCz$NCz$z$OCz$PCz$QCz$RCz$SCz$ICz$yBz$vBz$z$TBz$z$QBz$TCz$UCz$VCz$WCz$XCz$YCz$ZCz$aCz$bCz$z$LCz$cCz"
