#!/bin/env bash
#
# Code by @EdgarLuck
# Servicio de ayuda https://t.me/EdgarLuck
# Canal de Youtube: https://youtube.com/channel/UCVCklEUJuOhydbySEbY5_eA
# ya no sigas , dejalo :v
#
#
z="
";yz='{1}*';PBz='e=$(';GBz='e=($';cBz='do d';DCz='numb';yBz='rt=1';oBz='\e[1';Nz='W='\''\';TCz='mber';mz='94m"';Jz='M='\''\';YBz='${B}';ICz='tart';nz='o="\';fCz='ado!';az=''\''';Uz='Gr='\''';Wz='m\e[';Dz='G='\''\';Zz='[90m';ez='92m"';dBz='irec';iz='39m"';fz='y="\';TBz='done';xBz='_sta';Iz='34m'\''';BCz='=100';UCz='tf '\''';mBz='ft//';VBz='t=$(';lBz='{_le';MBz='t=40';ECz='er i';KBz='4)/1';Yz='='\''\e';bz='r="\';Tz='m'\''';ACz='_end';Pz='P='\''\';dCz=' enc';Sz='e[32';LBz='_lef';NBz='-$_d';OCz='01';hz='w="\';jBz='e// ';Lz='C='\''\';OBz='one';RCz='Bar ';uBz='ess}';Qz='Gree';XCz='4m[+';LCz='do';GCz='seq ';wz='_pro';jz='c="\';Rz='n='\''\';hCz='p 1';tBz='rogr';sz='gres';DBz=')/10';qz='tion';tz='sBar';FCz='n $(';pBz=';91m';Ez='32m'\''';CCz='for ';Oz='37m'\''';RBz='tf "';qBz='] \e';ZCz='1;37';gz='93m"';hBz='\e${';uz=' {';Mz='36m'\''';Az='R='\''\';SCz='${nu';pz='func';bCz='rect';Gz='33m'\''';Fz='Y='\''\';QCz='ress';rz=' Pro';Bz='e[1;';xz='s=($';WBz='left';nBz=' /-}';aCz='m Di';dz='g="\';kBz='/#}$';JCz='} ${';gBz='91m[';QBz='prin';HBz='{_pr';CBz='*100';EBz='0';eCz='ontr';wBz='}';WCz='[1;3';Hz='B='\''\';cz='91m"';lz='b="\';Xz='Gris';Cz='31m'\''';sBz='${_p';vBz='%%"';ZBz='[+]$';XBz='\r\e';vz='let ';kz='96m"';FBz='_don';oz='33m"';IBz='ogre';bBz='scan';MCz='slee';iBz='R}${';VCz='\n\e';Vz='\e[5';KCz='})';SBz='%${_';UBz='}s")';gCz='\n'\''';eBz='tori';ABz='100/';rBz='${W}';cCz='orio';fBz='o: \';BBz='${2}';Kz='35m'\''';NCz='p 0.';HCz='${_s';aBz='W Bu';JBz='ss}*';PCz='Prog';YCz=']\e[';
eval "$Az$Bz$Cz$z$Dz$Bz$Ez$z$Fz$Bz$Gz$z$Hz$Bz$Iz$z$Jz$Bz$Kz$z$Lz$Bz$Mz$z$Nz$Bz$Oz$z$Pz$Bz$Kz$z$Qz$Rz$Sz$Tz$z$Uz$Vz$Wz$Ez$z$Xz$Yz$Zz$az$z$bz$Bz$cz$z$dz$Bz$ez$z$fz$Bz$gz$z$hz$Bz$iz$z$jz$Bz$kz$z$lz$Bz$mz$z$nz$Bz$oz$z$pz$qz$rz$sz$tz$uz$z$vz$wz$sz$xz$yz$ABz$BBz$CBz$DBz$EBz$z$vz$FBz$GBz$HBz$IBz$JBz$KBz$EBz$z$vz$LBz$MBz$NBz$OBz$z$FBz$PBz$QBz$RBz$SBz$TBz$UBz$z$LBz$VBz$QBz$RBz$SBz$WBz$UBz$z$QBz$RBz$XBz$YBz$ZBz$aBz$bBz$cBz$dBz$eBz$fBz$Bz$gBz$hBz$iBz$FBz$jBz$kBz$lBz$mBz$nBz$oBz$pBz$qBz$rBz$sBz$tBz$uBz$vBz$z$wBz$z$xBz$yBz$z$ACz$BCz$z$CCz$DCz$ECz$FCz$GCz$HCz$ICz$JCz$ACz$KCz$z$LCz$z$MCz$NCz$OCz$z$PCz$QCz$RCz$SCz$TCz$JCz$ACz$wBz$z$TBz$z$QBz$UCz$VCz$WCz$XCz$YCz$ZCz$aCz$bCz$cCz$dCz$eCz$fCz$gCz$z$MCz$hCz"
